version: "3"
services:
  mariadb:
    image: remonlam/docker-wordpress-arm:mariadb-armhf
    environment:
    - MYSQL_ROOT_PASSWORD="rootpassword123"
    - YSQL_ROOT_PASSWORD="rootpassword123
    - MYSQL_DATABASE="wordpress"
    - MYSQL_USER="wordpress"
    - MYSQL_PASSWORD="password123"
    volumes:
      - type: bind
        source: /home/[user]/shared/mariadb
        target: /var/lib/mysq
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: always
    ports:
      - "3306:3306"
    networks:
      - backend

  wordpress:
    image: remonlam/docker-wordpress-arm:wordpress-armhf
    environment:
    - WORDPRESS_TABLE_PREFIX="wp_"
    - WORDPRESS_DB_HOST="mariadb"
    - WORDPRESS_DB_NAME="wordpress"
    - WORDPRESS_DB_USER="wordpress"
    - WORDPRESS_DB_PASSWORD="password123"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: always
    ports:
      - "9000:9000"
    networks:
      - backend
      - frontend

  nginx:
    image: remonlam/docker-wordpress-arm:nginx-armhf
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: always
    ports:
      - "80:80"
    networks:
      - frontend

networks:
  backend:
  frontend:
