version: "3"
services:
  mariadb:
]    image: remonlam/docker-wordpress-arm:mariadb-armhf
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"
    networks:
      - backend

  wordpress:
]    image: remonlam/docker-wordpress-arm:wordpress-armhf
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"
    networks:
      - backend
      - frontend


  nginx:
]    image: remonlam/docker-wordpress-arm:nginx-armhf
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - frontend



networks:
  backend:
  frontend:

docker run \
  --detach \
  --name mariadb \
  --volume /home/[user]/shared/mariadb:/var/lib/mysql \
  --env MYSQL_ROOT_PASSWORD="rootpassword123" \
  --env MYSQL_DATABASE="wordpress" \
  --env MYSQL_USER="wordpress" \
  --env MYSQL_PASSWORD="password123" \
  --publish 3306:3306 \
  remonlam/docker-wordpress-arm:mariadb-armhf
